version: "3.7"

services:
  app:
    image: hnaiyi/partkeepr-dev:latest
        # Use this instead if you want to develop the docker infrastructure
        #build:
            #context: ./app
            #args:
                #SRC_IMAGE: partkeepr/base-dev:latest
    ports:
      - 8082:80
    networks:
      partkeepr-internal:
        ipv4_address: 172.100.2.2
        aliases:
          - partkeepr-server
    volumes:
      - "../..:/var/www/pk"
    env_file:
      - ./github.env
    environment:
      GITHUB_DEBUG_UID: 1000
 
  db-instance:
    image: hnaiyi/mysql:partkeepr
    platform: linux/amd64
    volumes:
      - db-storage:/var/lib/mysql
    networks:
      partkeepr-internal:
        ipv4_address: 172.100.2.3
        aliases:
          - mysql-server
    environment:
      # See https://hub.docker.com/_/mysql for all available variables.
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: partkeepr
      MYSQL_ALLOW_EMPTY_PASSWORD: false

networks:
  partkeepr-internal:
    name: partkeepr-dev-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.2.0/24
          ip_range: 172.100.2.0/24
          gateway: 172.100.2.1

volumes:
  db-storage:
    name: partkeepr-data-prod
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/dockervolumes/partkeepr-mysql-prod"

